name: kardig
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.1 <4.0.0'

dependencies:
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Library  untuk Karcis Digital
  qr_flutter: ^4.1.0
  
  # Library milik untuk Kamera dan Database
  qr_code_scanner_plus: ^2.1.2
  permission_handler: ^12.0.0
  sqflite: ^2.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

# ICON APLIKASI
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/kardig.png"
  min_sdk_android: 21

  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/kardig.png"

# BOOT WARNA
flutter_native_splash:
  color: "#FF131314"
  image: "assets/icon/kardig.png"
  android_12: 
    color: "#FF131314"
    image: "assets/icon/kardig.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/kardig.png